# Generated by Django 4.1.5 on 2023-01-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_order_created_by_alter_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='departamento',
            field=models.CharField(max_length=15, null=True, verbose_name='Departamento'),
        ),
    ]
