# Generated by Django 4.1.5 on 2023-01-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_product_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='departamento',
            field=models.CharField(choices=[('AMAZONAS', 'Amazonas'), ('ANCASH', 'Áncash'), ('APURIMAC', 'Apurímac'), ('AREQUIPA', 'Arequipa'), ('AYACUCHO', 'Ayacucho'), ('CAJAMARCA', 'Cajamarca'), ('CALLAO', 'Callao'), ('CUSCO', 'Cusco'), ('HUANCAVELICA', 'Huancavelica'), ('HUANUCO', 'Huánuco'), ('ICA', 'Ica'), ('JUNIN', 'Junín'), ('LA_LIBERTAD', 'La Libertad'), ('LAMBAYEQUE', 'Lambayeque'), ('LIMA', 'Lima'), ('LORETO', 'Loreto'), ('MADRE_DE_DIOS', 'Madre de Dios'), ('MOQUEGUA', 'Moquegua'), ('PASCO', 'Pasco'), ('PIURA', 'Piura'), ('PUNO', 'Puno'), ('SAN_MARTIN', 'San Martín'), ('TACNA', 'Tacna'), ('TUMBES', 'Tumbes'), ('UCAYALI', 'Ucayali')], default='AREQUIPA', max_length=15, null=True, verbose_name='Departamento'),
        ),
    ]
