# Generated by Django 4.1.5 on 2023-01-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_product_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product_images/% Y/% m/% d/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product_images/% Y/% m/% d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product_images/% Y/% m/% d/'),
        ),
    ]
