# Generated by Django 4.1.5 on 2023-01-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_userprofile_first_name_userprofile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_vendor',
            field=models.BooleanField(default=False, verbose_name='Es vendedor?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='num_whatsapp',
            field=models.CharField(max_length=9, null=True, verbose_name='WhatsApp'),
        ),
    ]
