# Generated by Django 4.1.5 on 2023-01-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='departamento',
            field=models.CharField(choices=[('1', 'Amazonas'), ('2', 'Áncash'), ('3', 'Apurímac'), ('4', 'Arequipa'), ('5', 'Ayacucho'), ('6', 'Cajamarca'), ('7', 'Callao'), ('8', 'Cusco'), ('9', 'Huancavelica'), ('10', 'Huánuco'), ('11', 'Ica'), ('12', 'Junín'), ('13', 'La Libertad'), ('14', 'Lambayeque'), ('15', 'Lima'), ('16', 'Loreto'), ('17', 'Madre de Dios'), ('18', 'Moquegua'), ('19', 'Pasco'), ('20', 'Piura'), ('21', 'Puno'), ('22', 'San Martín'), ('23', 'Tacna'), ('24', 'Tumbes'), ('25', 'Ucayali')], default='15', max_length=15, null=True, verbose_name='Departamento'),
        ),
    ]
