# Generated by Django 4.1.5 on 2023-01-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_department_alter_userprofile_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(default='AREQUIPA', max_length=15, null=True),
        ),
    ]
