# Generated by Django 4.1.5 on 2023-01-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_alter_department_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(default='AREQUIPA', max_length=15, null=True, verbose_name='Filtrar por departamento'),
        ),
    ]
